# Generated by Django 3.1.4 on 2020-12-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
